stages:
  - build

pdflatex:
  stage: build
  image: radkappe/latex
  script:
    - latexmk -pdf demo.tex
    - latexmk -c demo.tex
    - latexmk -pdf bigsposter.tex
    - latexmk -c bigsposter.tex
    - tar -czvf nightly.tar.gz demo.pdf demo.tex bigsposter.pdf bigsposter.cls
  artifacts:
    paths:
      - bigsposter.pdf
      - nightly.tar.gz
